# GET http://localhost:3000/products

# GET http://localhost:3000/products/3

# POST http://localhost:3000/suppliers
# Content-Type: application/json 

# {
#   "name": "Evergreen Nursery",
#   "email": "support@evergreennursery.com",
#   "phone_number": "714-537-8877"
# }

PATCH http://localhost:3000/products/1
Content-Type: application/json 

{
  "supplier_id": 4
}

# DELETE http://localhost:3000/suppliers/1

