@hostname = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzE5ODY5NzV9.8uNN3TFXRY1WLh0HGgfHtErJGKVp4soH8URlQO4NKyY

# @jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzE2NDA1Mjl9.XDDO47TGrdS_q7uq0ai6f-ZbUHbBcc9mJSPVen3A2Ag randy, non admin

### product index
GET {{hostname}}/products?category=Flower
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzEzMDE4NzN9.06EXGEqzvxjFLwMr5BvfWJHJPVrEX02wyHqjxH9OENI

### show product

GET {{hostname}}/products/4

### create product

POST {{hostname}}/products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Bonsai Tree",
  "price": 90,
  "description": "Meticulous plant.",
  "supplier_id": 4,
  "inventory_count": 1
}

### update product

PATCH {{hostname}}/products/6
Content-Type: application/json 
Authorization: Bearer {{jwt}}

{
  "inventory_count": 2
}

### DELETE product

DELETE {{hostname}}/products/1
Authorization: Bearer {{jwt}}

### users create signup 

POST {{hostname}}/users 
Content-Type: application/json 

{
  "name": "jonathon ahn",
  "email": "jonathonahn@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### sessions create (login)
POST {{hostname}}/sessions 
Content-Type: application/json 

{
  "email": "jonathonahn@gmail.com",
  "password": "password"
}

### orders create 

POST {{hostname}}/orders
Content-Type: application/json 
Authorization: Bearer {{jwt}}


### orders show 
GET {{hostname}}/orders/6
Authorization: Bearer {{jwt}}

### orders index
GET {{hostname}}/orders/
Authorization: Bearer {{jwt}}

### cart product 
POST {{hostname}}/cart/
Content-Type: application/json 
Authorization: Bearer {{jwt}}

{
  "product_id": 2,
  "quantity": 3
}

### cart index 

GET {{hostname}}/cart/
Content-Type: application/json 
Authorization: Bearer {{jwt}}

### cart update 

PATCH {{hostname}}/cart/1
Content-Type: application/json 
Authorization: Bearer {{jwt}}



