###
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzEzMDE4NzN9.06EXGEqzvxjFLwMr5BvfWJHJPVrEX02wyHqjxH9OENI

###

GET http://localhost:3000/products/4

###

POST http://localhost:3000/images
Content-Type: application/json 

{
  "url": "",
  "product_id": 
}

###

PATCH http://localhost:3000/products/1
Content-Type: application/json 

{
  "supplier_id": 4
}

###

DELETE http://localhost:3000/suppliers/1

### users create signup 

POST http://localhost:3000/users 
Content-Type: application/json 

{
  "name": "jonathon ahn",
  "email": "jonathonahn@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### sessions create (login)
POST http://localhost:3000/sessions 
Content-Type: application/json 

{
  "email": "jonathonahn@gmail.com",
  "password": "password"
}

### orders create 

POST http://localhost:3000/orders
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzEzODY5ODJ9.PGd5kfumbsK1qqIyoX6jGiSuHMoDrp8vKZ6U0DZkXCs

{
  "product_id": 2,
  "quantity": 5
}

### orders show 
GET http://localhost:3000/orders/6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzEzODgxMTR9.JL6elEeYqy0MqFPEHHitEkr3b3qHejms8or6j1iawi4

### orders index
GET http://localhost:3000/orders/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzEzODgxMTR9.JL6elEeYqy0MqFPEHHitEkr3b3qHejms8or6j1iawi4
